### ISSUE TITLE
Skip detection of XAML members or detect call to InitializeComponent

### ISSUE THREAD

**Issue by cmeeren** [ulrichb/ImplicitNullability#11] opened 2017-03-22 09:14 UTC
When working with XAML, it complains that class members (fields, in this case) defined in XAML (using `x:Name`) are not initialized on all excecution paths, even though `InitializeComponent()` is called in the constructor.

Is it possible to detect the call to `InitializeComponent()` or otherwise skip detection of XAML members?

![capture](https://cloud.githubusercontent.com/assets/7766733/24190226/46c0b59a-0ee8-11e7-871d-838055119035.PNG)

**Comment by ulrichb** [comment] 2017-04-01 19:14
Thanks for your interesting bug report. It is interesting because it uncovered two problems at once.

In my repro sample these fields for the XAML controls (which are the cause for your c'tor warning) occur _two times in ReSharper's code model_. First as "IXamlField" (representing the control element in the `.xaml` file) and a second time as "real" C# field in the _compiler-generated_ `<Control>.g.i.cs` file (placed in the obj directory).

=> To solve your issue we a) have to exclude the "IXamlField" (which is no problem) and b) we somehow have to exclude the field in the generated code file too.

The second exclusion is a problem because we cannot easily determine that this is a "XAML generated control field".

_But:_ It uncovered a general issue in Implicit Nullability, the handling if generated code (not just these XAML fields). I'm not 100% sure it it will be the final solution but I'm thinking about providing an option to exclude generated code from Implicit Nullability (ReSharper's configuration already provides a possibility to determine which code elements should be considered "generated"). Reasoning: In general Implicit Nullability only marks code as implicitly NotNull where the developer is able to opt-out (using CanBeNull / ItemCanBeNull attributes). As many of the code generation tools don't handle nullability (and don't eject these attributes) there should be an option to exclude their output from Implicit Nullability. Further in many examples (like the XAML generator) there isn't even a possibility to override the generated fields manually.

In [a branch](https://github.com/ulrichb/ImplicitNullability/tree/ExclusionGeneratedCode) I implemented a spike which excludes XAML field and all generated code (at the moment not configurable). 

@cmeeren: Could you build it or grab a build [from the CI](https://ci.appveyor.com/project/ulrichb/implicitnullability/build/3.5.1.701/artifacts) and test it? I would love to hear feedback.

**Comment by cmeeren** [comment] 2017-04-01 19:59
Sure, I'll give it a spin when I have the time. But in general, yes, I think that excluding generated code is the correct choice in general.

**Comment by cmeeren** [comment] 2017-04-03 12:02
I'm not able to install it. I expect that is because my installed version is 3.6.0.20171-pre02 and the one from the CI is 3.5.1.20171.

**Comment by ulrichb** [comment] 2017-04-03 12:18
Oh, yes, ..

First you have to uninstall the current version of IN, and then you have to configure R# this way and install it again using the extension manager (after copying the .nupkg file into a local temp dir):

![image](https://cloud.githubusercontent.com/assets/388796/24608790/55102808-1878-11e7-8d04-adc7c8a42de8.png)


BTW: Don't worry about the lower version, the .nupkg contains everything which is contained by 3.6.0.20171-pre02 (+ more).

Thanks in advance for testing this.

PS: You _could_ (optionally) also test this in a VS experimental instance, see https://www.jetbrains.com/help/resharper/sdk/Extensions/Deployment/LocalInstallation/ExperimentalInstance.html.

**Comment by cmeeren** [comment] 2017-04-03 12:40
Thanks. It works, the warning is gone. :)

**Comment by ulrichb** [comment] 2017-04-03 14:56
Any other problems (i.e. "false negative implicit [NotNulls]") with the generated code exclusion?

**Comment by cmeeren** [comment] 2017-04-03 17:00
Are you talking about implicit NotNulls that should be there, but aren't?

**Comment by ulrichb** [comment] 2017-04-03 17:03
Exactly. In other words: Do you experience any excluded, previously implicit [NotNull] code parts due to the "generated code exclusion" which shouldn't be excluded?

**Comment by cmeeren** [comment] 2017-04-04 06:31
Everything seems to work perfectly.

**Comment by ulrichb** [comment] 2017-04-05 08:39
@cmeeren Sry, the generated code exclusion (+ the fix for "XAML fields") didn't get it into the 3.6.0 release (there is one last open question).

But: I've updated the [branch](https://github.com/ulrichb/ImplicitNullability/tree/ExclusionGeneratedCode), so you can use the [latest artifact from the CI](https://ci.appveyor.com/project/ulrichb/implicitnullability/branch/ExclusionGeneratedCode/artifacts) to get all 3.6.0 changes + the fix for your issue.

**Comment by cmeeren** [comment] 2017-04-05 08:40
Thanks. No problem, I'll wait for the official release. :)

**Comment by ulrichb** [comment] 2017-05-11 23:16
Fixed with 3.7.0 (requires enabling "exclude generated code" option).

**Closed by ulrichb** 2017-05-11 23:16 UTC
Labels: bug
